### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/infografia-de-hilos-bg55-a#2]
[Infografia Hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-bg55-a/files/8375064/Infografia.Hilos.pdf)

**Comment by EvelynLopezz** [comment]
Calificación de la infografía de Adolfo Vásquez Rojas:
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
